<?php
/**
 * FileUploadApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Docbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DOCBOX® API
 *
 * The DOCBOX® REST API makes it possible to integrate the DOCBOX® into third-party programs such as ERP or CRM applications. The third-party programs can access certain DOCBOX® functions, for example to archive documents in the DOCBOX® or to search for documents in it.  The api is available under https://{docbox-host}:{api-port}/api/v2. The default port is 8081 and should not be mistaken with the port of the webapp.  To authenticate to the API you must pass the API-Key header. Api keys can be configured by administrators in the modules->API section. If you are using the cloud version of DOCBOX® you must also pass the Cloud-ID header with your Cloudid.
 *
 * The version of the OpenAPI document: 7.6.0
 * Contact: support@docbox.eu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Docbox\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\Docbox\ApiException;
use OpenAPI\Client\Docbox\Configuration;
use OpenAPI\Client\Docbox\HeaderSelector;
use OpenAPI\Client\Docbox\ObjectSerializer;

/**
 * FileUploadApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Docbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FileUploadApi
{
    protected \GuzzleHttp\ClientInterface $client;

    protected \OpenAPI\Client\Docbox\Configuration $config;

    protected \OpenAPI\Client\Docbox\HeaderSelector $headerSelector;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'fileUpload' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $configuration = null,
        HeaderSelector $headerSelector = null,
        protected $hostIndex = 0
    ) {
        $this->client = $client instanceof \GuzzleHttp\ClientInterface ? $client : new Client();
        $this->config = $configuration instanceof \OpenAPI\Client\Docbox\Configuration ? $configuration : new Configuration();
        $this->headerSelector = $headerSelector instanceof \OpenAPI\Client\Docbox\HeaderSelector ? $headerSelector : new HeaderSelector();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    public function getConfig(): \OpenAPI\Client\Docbox\Configuration
    {
        return $this->config;
    }

    /**
     * Operation fileUpload
     *
     * File upload
     *
     * @param  string $targetMandatorName Name of the mandator where the document should be archived (optional)
     * @param  string $targetFolderPath Path to the target folder starting at the mandator. Either this or &#x60;target-folder-id&#x60; is required. Example: \\\&quot;/Eingangsrechnungen/2018/\\\&quot; (optional)
     * @param  int $targetFolderId Id of the target folder. Either this or &#x60;target-folder-path&#x60; is required. (optional)
     * @param  string $targetDocumentName targetDocumentName (optional)
     * @param  \SplFileObject $uploadData The file to upload. Either this or &#x60;upload-data-base64&#x60; is required. (optional)
     * @param  string $uploadDataBase64 Base64 encoded content of the upload-data. When using this parameter &#x60;target-document-name&#x60; is required. Either this or &#x60;upload-data&#x60; is required. (optional)
     * @param  string $keywords Comma separated list of keywords. Commas can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $documentTypes Comma separated list of document types (or their alias). Commas can be escaped by prepending \\\\\\\\. Ignores values where no document-type was found. (optional)
     * @param  string $externalId externalId (optional)
     * @param  string $externalMetadatas Comma separated list of key&#x3D;value pairs. Comma and equals signs can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $emailImportOrder emailImportOrder (optional)
     * @param  bool $forceNewDocument forceNewDocument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fileUpload'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Docbox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return int
     */
    public function fileUpload($targetMandatorName = null, $targetFolderPath = null, $targetFolderId = null, $targetDocumentName = null, $uploadData = null, $uploadDataBase64 = null, $keywords = null, $documentTypes = null, $externalId = null, $externalMetadatas = null, $emailImportOrder = null, $forceNewDocument = null, string $contentType = self::contentTypes['fileUpload'][0])
    {
        [$response] = $this->fileUploadWithHttpInfo($targetMandatorName, $targetFolderPath, $targetFolderId, $targetDocumentName, $uploadData, $uploadDataBase64, $keywords, $documentTypes, $externalId, $externalMetadatas, $emailImportOrder, $forceNewDocument, $contentType);
        return $response;
    }

    /**
     * Operation fileUploadWithHttpInfo
     *
     * File upload
     *
     * @param  string $targetMandatorName Name of the mandator where the document should be archived (optional)
     * @param  string $targetFolderPath Path to the target folder starting at the mandator. Either this or &#x60;target-folder-id&#x60; is required. Example: \\\&quot;/Eingangsrechnungen/2018/\\\&quot; (optional)
     * @param  int $targetFolderId Id of the target folder. Either this or &#x60;target-folder-path&#x60; is required. (optional)
     * @param  string $targetDocumentName (optional)
     * @param  \SplFileObject $uploadData The file to upload. Either this or &#x60;upload-data-base64&#x60; is required. (optional)
     * @param  string $uploadDataBase64 Base64 encoded content of the upload-data. When using this parameter &#x60;target-document-name&#x60; is required. Either this or &#x60;upload-data&#x60; is required. (optional)
     * @param  string $keywords Comma separated list of keywords. Commas can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $documentTypes Comma separated list of document types (or their alias). Commas can be escaped by prepending \\\\\\\\. Ignores values where no document-type was found. (optional)
     * @param  string $externalId (optional)
     * @param  string $externalMetadatas Comma separated list of key&#x3D;value pairs. Comma and equals signs can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $emailImportOrder (optional)
     * @param  bool $forceNewDocument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fileUpload'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Docbox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of int, HTTP status code, HTTP response headers (array of strings)
     */
    public function fileUploadWithHttpInfo($targetMandatorName = null, $targetFolderPath = null, $targetFolderId = null, $targetDocumentName = null, $uploadData = null, $uploadDataBase64 = null, $keywords = null, $documentTypes = null, $externalId = null, $externalMetadatas = null, $emailImportOrder = null, $forceNewDocument = null, string $contentType = self::contentTypes['fileUpload'][0])
    {
        $request = $this->fileUploadRequest($targetMandatorName, $targetFolderPath, $targetFolderId, $targetDocumentName, $uploadData, $uploadDataBase64, $keywords, $documentTypes, $externalId, $externalMetadatas, $emailImportOrder, $forceNewDocument, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            if ($statusCode === 200) {
                if ('int' === '\SplFileObject') {
                    $content = $response->getBody(); //stream goes to serializer
                } else {
                    $content = (string) $response->getBody();
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }

                return [
                    ObjectSerializer::deserialize($content, 'int', []),
                    $response->getStatusCode(),
                    $response->getHeaders()
                ];
            }

            $returnType = 'int';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $content
                    );
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 200) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    'int',
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
            }

            throw $apiException;
        }
    }

    /**
     * Operation fileUploadAsync
     *
     * File upload
     *
     * @param  string $targetMandatorName Name of the mandator where the document should be archived (optional)
     * @param  string $targetFolderPath Path to the target folder starting at the mandator. Either this or &#x60;target-folder-id&#x60; is required. Example: \\\&quot;/Eingangsrechnungen/2018/\\\&quot; (optional)
     * @param  int $targetFolderId Id of the target folder. Either this or &#x60;target-folder-path&#x60; is required. (optional)
     * @param  string $targetDocumentName (optional)
     * @param  \SplFileObject $uploadData The file to upload. Either this or &#x60;upload-data-base64&#x60; is required. (optional)
     * @param  string $uploadDataBase64 Base64 encoded content of the upload-data. When using this parameter &#x60;target-document-name&#x60; is required. Either this or &#x60;upload-data&#x60; is required. (optional)
     * @param  string $keywords Comma separated list of keywords. Commas can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $documentTypes Comma separated list of document types (or their alias). Commas can be escaped by prepending \\\\\\\\. Ignores values where no document-type was found. (optional)
     * @param  string $externalId (optional)
     * @param  string $externalMetadatas Comma separated list of key&#x3D;value pairs. Comma and equals signs can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $emailImportOrder (optional)
     * @param  bool $forceNewDocument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fileUpload'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function fileUploadAsync($targetMandatorName = null, $targetFolderPath = null, $targetFolderId = null, $targetDocumentName = null, $uploadData = null, $uploadDataBase64 = null, $keywords = null, $documentTypes = null, $externalId = null, $externalMetadatas = null, $emailImportOrder = null, $forceNewDocument = null, string $contentType = self::contentTypes['fileUpload'][0]): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->fileUploadAsyncWithHttpInfo($targetMandatorName, $targetFolderPath, $targetFolderId, $targetDocumentName, $uploadData, $uploadDataBase64, $keywords, $documentTypes, $externalId, $externalMetadatas, $emailImportOrder, $forceNewDocument, $contentType)
            ->then(
                static fn($response) => $response[0]
            );
    }

    /**
     * Operation fileUploadAsyncWithHttpInfo
     *
     * File upload
     *
     * @param  string $targetMandatorName Name of the mandator where the document should be archived (optional)
     * @param  string $targetFolderPath Path to the target folder starting at the mandator. Either this or &#x60;target-folder-id&#x60; is required. Example: \\\&quot;/Eingangsrechnungen/2018/\\\&quot; (optional)
     * @param  int $targetFolderId Id of the target folder. Either this or &#x60;target-folder-path&#x60; is required. (optional)
     * @param  string $targetDocumentName (optional)
     * @param  \SplFileObject $uploadData The file to upload. Either this or &#x60;upload-data-base64&#x60; is required. (optional)
     * @param  string $uploadDataBase64 Base64 encoded content of the upload-data. When using this parameter &#x60;target-document-name&#x60; is required. Either this or &#x60;upload-data&#x60; is required. (optional)
     * @param  string $keywords Comma separated list of keywords. Commas can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $documentTypes Comma separated list of document types (or their alias). Commas can be escaped by prepending \\\\\\\\. Ignores values where no document-type was found. (optional)
     * @param  string $externalId (optional)
     * @param  string $externalMetadatas Comma separated list of key&#x3D;value pairs. Comma and equals signs can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $emailImportOrder (optional)
     * @param  bool $forceNewDocument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fileUpload'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function fileUploadAsyncWithHttpInfo($targetMandatorName = null, $targetFolderPath = null, $targetFolderId = null, $targetDocumentName = null, $uploadData = null, $uploadDataBase64 = null, $keywords = null, $documentTypes = null, $externalId = null, $externalMetadatas = null, $emailImportOrder = null, $forceNewDocument = null, string $contentType = self::contentTypes['fileUpload'][0]): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = 'int';
        $request = $this->fileUploadRequest($targetMandatorName, $targetFolderPath, $targetFolderId, $targetDocumentName, $uploadData, $uploadDataBase64, $keywords, $documentTypes, $externalId, $externalMetadatas, $emailImportOrder, $forceNewDocument, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                static function ($response) use ($returnType) : array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        $content = json_decode($content);
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                static function ($exception) : void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'fileUpload'
     *
     * @param  string $targetMandatorName Name of the mandator where the document should be archived (optional)
     * @param  string $targetFolderPath Path to the target folder starting at the mandator. Either this or &#x60;target-folder-id&#x60; is required. Example: \\\&quot;/Eingangsrechnungen/2018/\\\&quot; (optional)
     * @param  int $targetFolderId Id of the target folder. Either this or &#x60;target-folder-path&#x60; is required. (optional)
     * @param  string $targetDocumentName (optional)
     * @param  \SplFileObject $uploadData The file to upload. Either this or &#x60;upload-data-base64&#x60; is required. (optional)
     * @param  string $uploadDataBase64 Base64 encoded content of the upload-data. When using this parameter &#x60;target-document-name&#x60; is required. Either this or &#x60;upload-data&#x60; is required. (optional)
     * @param  string $keywords Comma separated list of keywords. Commas can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $documentTypes Comma separated list of document types (or their alias). Commas can be escaped by prepending \\\\\\\\. Ignores values where no document-type was found. (optional)
     * @param  string $externalId (optional)
     * @param  string $externalMetadatas Comma separated list of key&#x3D;value pairs. Comma and equals signs can be escaped by prepending \\\\\\\\. (optional)
     * @param  string $emailImportOrder (optional)
     * @param  bool $forceNewDocument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fileUpload'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function fileUploadRequest($targetMandatorName = null, $targetFolderPath = null, $targetFolderId = null, $targetDocumentName = null, $uploadData = null, $uploadDataBase64 = null, $keywords = null, $documentTypes = null, $externalId = null, $externalMetadatas = null, $emailImportOrder = null, $forceNewDocument = null, string $contentType = self::contentTypes['fileUpload'][0]): \GuzzleHttp\Psr7\Request
    {














        $resourcePath = '/file-upload';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($targetMandatorName !== null) {
            $formParams['target-mandator-name'] = ObjectSerializer::toFormValue($targetMandatorName);
        }

        // form params
        if ($targetFolderPath !== null) {
            $formParams['target-folder-path'] = ObjectSerializer::toFormValue($targetFolderPath);
        }

        // form params
        if ($targetFolderId !== null) {
            $formParams['target-folder-id'] = ObjectSerializer::toFormValue($targetFolderId);
        }

        // form params
        if ($targetDocumentName !== null) {
            $formParams['target-document-name'] = ObjectSerializer::toFormValue($targetDocumentName);
        }

        // form params
        if ($uploadData !== null) {
            $multipart = true;
            $formParams['upload-data'] = [];
            $paramFiles = is_array($uploadData) ? $uploadData : [$uploadData];
            foreach ($paramFiles as $paramFile) {
                $formParams['upload-data'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        // form params
        if ($uploadDataBase64 !== null) {
            $formParams['upload-data-base64'] = ObjectSerializer::toFormValue($uploadDataBase64);
        }

        // form params
        if ($keywords !== null) {
            $formParams['keywords'] = ObjectSerializer::toFormValue($keywords);
        }

        // form params
        if ($documentTypes !== null) {
            $formParams['document-types'] = ObjectSerializer::toFormValue($documentTypes);
        }

        // form params
        if ($externalId !== null) {
            $formParams['external-id'] = ObjectSerializer::toFormValue($externalId);
        }

        // form params
        if ($externalMetadatas !== null) {
            $formParams['external-metadatas'] = ObjectSerializer::toFormValue($externalMetadatas);
        }

        // form params
        if ($emailImportOrder !== null) {
            $formParams['email-import-order'] = ObjectSerializer::toFormValue($emailImportOrder);
        }

        // form params
        if ($forceNewDocument !== null) {
            $formParams['force-new-document'] = ObjectSerializer::toFormValue($forceNewDocument);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Cloud-ID');
        if ($apiKey !== null) {
            $headers['Cloud-ID'] = $apiKey;
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('API-Key');
        if ($apiKey !== null) {
            $headers['API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
