<?php
/**
 * PageApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Docbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DOCBOX® API
 *
 * The DOCBOX® REST API makes it possible to integrate the DOCBOX® into third-party programs such as ERP or CRM applications. The third-party programs can access certain DOCBOX® functions, for example to archive documents in the DOCBOX® or to search for documents in it.  The api is available under https://{docbox-host}:{api-port}/api/v2. The default port is 8081 and should not be mistaken with the port of the webapp.  To authenticate to the API you must pass the API-Key header. Api keys can be configured by administrators in the modules->API section. If you are using the cloud version of DOCBOX® you must also pass the Cloud-ID header with your Cloudid.
 *
 * The version of the OpenAPI document: 7.6.0
 * Contact: support@docbox.eu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Docbox\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\Docbox\ApiException;
use OpenAPI\Client\Docbox\Configuration;
use OpenAPI\Client\Docbox\HeaderSelector;
use OpenAPI\Client\Docbox\ObjectSerializer;

/**
 * PageApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Docbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PageApi
{
    protected \GuzzleHttp\ClientInterface $client;

    protected \OpenAPI\Client\Docbox\Configuration $config;

    protected \OpenAPI\Client\Docbox\HeaderSelector $headerSelector;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'pageOcrResult' => [
            'application/json',
        ],
        'pagePreview' => [
            'application/json',
        ],
    ];

    /**
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $configuration = null,
        HeaderSelector $headerSelector = null,
        protected $hostIndex = 0
    ) {
        $this->client = $client instanceof \GuzzleHttp\ClientInterface ? $client : new Client();
        $this->config = $configuration instanceof \OpenAPI\Client\Docbox\Configuration ? $configuration : new Configuration();
        $this->headerSelector = $headerSelector instanceof \OpenAPI\Client\Docbox\HeaderSelector ? $headerSelector : new HeaderSelector();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    public function getConfig(): \OpenAPI\Client\Docbox\Configuration
    {
        return $this->config;
    }

    /**
     * Operation pageOcrResult
     *
     * Returns the OCR-result of a page
     *
     * @param  int $id Page id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pageOcrResult'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Docbox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function pageOcrResult($id, string $contentType = self::contentTypes['pageOcrResult'][0])
    {
        [$response] = $this->pageOcrResultWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation pageOcrResultWithHttpInfo
     *
     * Returns the OCR-result of a page
     *
     * @param  int $id Page id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pageOcrResult'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Docbox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function pageOcrResultWithHttpInfo($id, string $contentType = self::contentTypes['pageOcrResult'][0])
    {
        $request = $this->pageOcrResultRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            if ($statusCode === 200) {
                if ('string' === '\SplFileObject') {
                    $content = $response->getBody(); //stream goes to serializer
                } else {
                    $content = (string) $response->getBody();
                    if ('string' !== 'string') {
                        try {
                            $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                        } catch (\JsonException) {
                            throw new ApiException(
                                sprintf(
                                    'Error JSON decoding server response (%s)',
                                    $request->getUri()
                                ),
                                $statusCode,
                                $response->getHeaders(),
                                $content
                            );
                        }
                    }
                }

                return [
                    ObjectSerializer::deserialize($content, 'string', []),
                    $response->getStatusCode(),
                    $response->getHeaders()
                ];
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 200) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    'string',
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
            }

            throw $apiException;
        }
    }

    /**
     * Operation pageOcrResultAsync
     *
     * Returns the OCR-result of a page
     *
     * @param  int $id Page id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pageOcrResult'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function pageOcrResultAsync($id, string $contentType = self::contentTypes['pageOcrResult'][0]): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->pageOcrResultAsyncWithHttpInfo($id, $contentType)
            ->then(
                static fn($response) => $response[0]
            );
    }

    /**
     * Operation pageOcrResultAsyncWithHttpInfo
     *
     * Returns the OCR-result of a page
     *
     * @param  int $id Page id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pageOcrResult'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function pageOcrResultAsyncWithHttpInfo($id, string $contentType = self::contentTypes['pageOcrResult'][0]): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = 'string';
        $request = $this->pageOcrResultRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                static function ($response) use ($returnType) : array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                static function ($exception) : void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'pageOcrResult'
     *
     * @param  int $id Page id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pageOcrResult'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function pageOcrResultRequest($id, string $contentType = self::contentTypes['pageOcrResult'][0]): \GuzzleHttp\Psr7\Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling pageOcrResult'
            );
        }


        $resourcePath = '/page/{id}/ocr-result';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Cloud-ID');
        if ($apiKey !== null) {
            $headers['Cloud-ID'] = $apiKey;
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('API-Key');
        if ($apiKey !== null) {
            $headers['API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation pagePreview
     *
     * Page preview
     *
     * @param  int $id id (required)
     * @param  int $bboxWidth bboxWidth (optional)
     * @param  int $bboxHeight bboxHeight (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pagePreview'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Docbox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function pagePreview($id, $bboxWidth = null, $bboxHeight = null, string $contentType = self::contentTypes['pagePreview'][0])
    {
        [$response] = $this->pagePreviewWithHttpInfo($id, $bboxWidth, $bboxHeight, $contentType);
        return $response;
    }

    /**
     * Operation pagePreviewWithHttpInfo
     *
     * Page preview
     *
     * @param  int $id (required)
     * @param  int $bboxWidth (optional)
     * @param  int $bboxHeight (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pagePreview'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Docbox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function pagePreviewWithHttpInfo($id, $bboxWidth = null, $bboxHeight = null, string $contentType = self::contentTypes['pagePreview'][0])
    {
        $request = $this->pagePreviewRequest($id, $bboxWidth, $bboxHeight, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            if ($statusCode === 200) {
                if ('\SplFileObject' === '\SplFileObject') {
                    $content = $response->getBody(); //stream goes to serializer
                } else {
                    $content = (string) $response->getBody();
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }

                return [
                    ObjectSerializer::deserialize($content, '\SplFileObject', []),
                    $response->getStatusCode(),
                    $response->getHeaders()
                ];
            }

            $returnType = '\SplFileObject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $content
                    );
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 200) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    '\SplFileObject',
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
            }

            throw $apiException;
        }
    }

    /**
     * Operation pagePreviewAsync
     *
     * Page preview
     *
     * @param  int $id (required)
     * @param  int $bboxWidth (optional)
     * @param  int $bboxHeight (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pagePreview'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function pagePreviewAsync($id, $bboxWidth = null, $bboxHeight = null, string $contentType = self::contentTypes['pagePreview'][0]): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->pagePreviewAsyncWithHttpInfo($id, $bboxWidth, $bboxHeight, $contentType)
            ->then(
                static fn($response) => $response[0]
            );
    }

    /**
     * Operation pagePreviewAsyncWithHttpInfo
     *
     * Page preview
     *
     * @param  int $id (required)
     * @param  int $bboxWidth (optional)
     * @param  int $bboxHeight (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pagePreview'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function pagePreviewAsyncWithHttpInfo($id, $bboxWidth = null, $bboxHeight = null, string $contentType = self::contentTypes['pagePreview'][0]): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = '\SplFileObject';
        $request = $this->pagePreviewRequest($id, $bboxWidth, $bboxHeight, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                static function ($response) use ($returnType) : array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        $content = json_decode($content);
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                static function ($exception) : void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'pagePreview'
     *
     * @param  int $id (required)
     * @param  int $bboxWidth (optional)
     * @param  int $bboxHeight (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['pagePreview'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function pagePreviewRequest($id, $bboxWidth = null, $bboxHeight = null, string $contentType = self::contentTypes['pagePreview'][0]): \GuzzleHttp\Psr7\Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling pagePreview'
            );
        }




        $resourcePath = '/page/{id}/preview';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $bboxWidth,
            'bbox-width', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $bboxHeight,
            'bbox-height', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['image/jpeg', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Cloud-ID');
        if ($apiKey !== null) {
            $headers['Cloud-ID'] = $apiKey;
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('API-Key');
        if ($apiKey !== null) {
            $headers['API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
