<?php
/**
 * SearchApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Docbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DOCBOX® API
 *
 * The DOCBOX® REST API makes it possible to integrate the DOCBOX® into third-party programs such as ERP or CRM applications. The third-party programs can access certain DOCBOX® functions, for example to archive documents in the DOCBOX® or to search for documents in it.  The api is available under https://{docbox-host}:{api-port}/api/v2. The default port is 8081 and should not be mistaken with the port of the webapp.  To authenticate to the API you must pass the API-Key header. Api keys can be configured by administrators in the modules->API section. If you are using the cloud version of DOCBOX® you must also pass the Cloud-ID header with your Cloudid.
 *
 * The version of the OpenAPI document: 7.6.0
 * Contact: support@docbox.eu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Docbox\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\Docbox\ApiException;
use OpenAPI\Client\Docbox\Configuration;
use OpenAPI\Client\Docbox\HeaderSelector;
use OpenAPI\Client\Docbox\ObjectSerializer;

/**
 * SearchApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Docbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'searchPOST' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation searchPOST
     *
     * @param  int $paginationSize Anzahl der Dokumente die im Ergebnis maximal zurückgegeben werden sollen, d.h. dieser Parameter gibt die Größe des Ergbnisfensters für das Paging des Suchergebnisses an. (optional, default to 10)
     * @param  int $paginationPage Gibt den Index des Ergebnisfensters an, welches angezeigt werden soll. Das erste Ergebnisfenster entspricht dabei dem Index 0. Durch Erhöhung des Index um 1 gelangt man zum nächsten Ergebnisfenster mit den nächsten Suchtreffern. Beispiel: Bei 27 gefundenen Dokumenten insgesamt und einer pagination-size von 10 liegt der Index des Ergebnisfensters zwischen 0 und 2 (optional, default to 0)
     * @param  string $fulltextAll Liste mit Texten, die alle gemeinsam auf jeder Trefferseite vorkommen müssen. (optional)
     * @param  string $fulltextOne Liste mit Texten, von denen mindestens einer auf jeder Trefferseite vorkommen muss. (optional)
     * @param  string $fulltextNone Liste mit Texten, von denen keiner auf den Trefferseiten vorkommen darf. (optional)
     * @param  string $fromDate Sucht nur nach Seiten deren Erstelldatum nach diesem Zeitpunkt liegt. (optional)
     * @param  string $toDate Sucht nur nach Seiten deren Erstelldatum vor diesem Zeitpunkt liegt. (optional)
     * @param  string $followupTerms Liste mit Texten die alle gemeinsam in den Wiedervorlage-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $noteTerms Liste mit Texten die alle gemeinsam in den Notiz-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $keywordTerms Liste von Texten die alle gemeinsam in den Schlagwörtern einer Seite vorkommen müssen. (optional)
     * @param  string $stampsInclusive Liste mit Namen aller Stempel, die gemeinsam auf einer Seite vorkommen müssen. (optional)
     * @param  string $stampsExclusive Liste mit Namen aller Stempel, von denen keiner auf einer Seite vorkommen darf. (optional)
     * @param  string $documentNameTerms Liste von Texten die alle im Dokumentennamen einer Seite vorkommen müssen. (optional)
     * @param  string $folderNameTerms Liste von Texten die alle im Ordner-Pfad einer Seite vorkommen müssen. (optional)
     * @param  string $location Pfad zu einem Ordner, auf den die Suche beschränkt werden soll (z. B. „/Muster GmbH/Rechnungen/“, „INBOX/Administrator“). Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  int $locationFolderId Ordner-Id, auf den die Suche beschränkt werden soll. Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  bool $recursive Bestimmt ob auch in Unterordner bei location gesucht wird. (optional, default to true)
     * @param  int $archiverId ID des Users der die zu suchenden Seiten archiviert haben muss. (optional)
     * @param  string $workflowName Name des Workflows in dem sich die zu suchenden Seiten aktuell befinden müssen. Durch Angabe von „*“ wird in allen Workflows gesucht. (optional)
     * @param  string $workflowState Name des Workflow-Knotens, in dem sich die zu suchenden Seiten aktuell befinden müssen. (optional)
     * @param  string $documentType Name oder Alias-Name eines Dokumenten-Typs, der allen zu suchenden Dokumenten zugewiesen sein muss. (optional)
     * @param  bool $includeTrash Gibt an, ob auch Dokumente im Papierkorb mit durchsucht werden sollen. (optional, default to false)
     * @param  string $externalId Text der in einer externen ID eines Dokuments vorkommen muss, damit es gefunden wird. (optional)
     * @param  string $externalMetadata Sucht Dokumente anhand ihrer externen Metadaten. Für jedes Metadatum in der Liste muss einem Dokument, damit es gefunden wird, ebenfalls ein Metadatum mit genau diesem Key zugeordnet sein und dessen Value den zu suchenden Value enthalten (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPOST'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Docbox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Docbox\Model\SearchPOST200Response
     */
    public function searchPOST($paginationSize = 10, $paginationPage = 0, $fulltextAll = null, $fulltextOne = null, $fulltextNone = null, $fromDate = null, $toDate = null, $followupTerms = null, $noteTerms = null, $keywordTerms = null, $stampsInclusive = null, $stampsExclusive = null, $documentNameTerms = null, $folderNameTerms = null, $location = null, $locationFolderId = null, $recursive = true, $archiverId = null, $workflowName = null, $workflowState = null, $documentType = null, $includeTrash = false, $externalId = null, $externalMetadata = null, string $contentType = self::contentTypes['searchPOST'][0])
    {
        list($response) = $this->searchPOSTWithHttpInfo($paginationSize, $paginationPage, $fulltextAll, $fulltextOne, $fulltextNone, $fromDate, $toDate, $followupTerms, $noteTerms, $keywordTerms, $stampsInclusive, $stampsExclusive, $documentNameTerms, $folderNameTerms, $location, $locationFolderId, $recursive, $archiverId, $workflowName, $workflowState, $documentType, $includeTrash, $externalId, $externalMetadata, $contentType);
        return $response;
    }

    /**
     * Operation searchPOSTWithHttpInfo
     *
     * @param  int $paginationSize Anzahl der Dokumente die im Ergebnis maximal zurückgegeben werden sollen, d.h. dieser Parameter gibt die Größe des Ergbnisfensters für das Paging des Suchergebnisses an. (optional, default to 10)
     * @param  int $paginationPage Gibt den Index des Ergebnisfensters an, welches angezeigt werden soll. Das erste Ergebnisfenster entspricht dabei dem Index 0. Durch Erhöhung des Index um 1 gelangt man zum nächsten Ergebnisfenster mit den nächsten Suchtreffern. Beispiel: Bei 27 gefundenen Dokumenten insgesamt und einer pagination-size von 10 liegt der Index des Ergebnisfensters zwischen 0 und 2 (optional, default to 0)
     * @param  string $fulltextAll Liste mit Texten, die alle gemeinsam auf jeder Trefferseite vorkommen müssen. (optional)
     * @param  string $fulltextOne Liste mit Texten, von denen mindestens einer auf jeder Trefferseite vorkommen muss. (optional)
     * @param  string $fulltextNone Liste mit Texten, von denen keiner auf den Trefferseiten vorkommen darf. (optional)
     * @param  string $fromDate Sucht nur nach Seiten deren Erstelldatum nach diesem Zeitpunkt liegt. (optional)
     * @param  string $toDate Sucht nur nach Seiten deren Erstelldatum vor diesem Zeitpunkt liegt. (optional)
     * @param  string $followupTerms Liste mit Texten die alle gemeinsam in den Wiedervorlage-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $noteTerms Liste mit Texten die alle gemeinsam in den Notiz-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $keywordTerms Liste von Texten die alle gemeinsam in den Schlagwörtern einer Seite vorkommen müssen. (optional)
     * @param  string $stampsInclusive Liste mit Namen aller Stempel, die gemeinsam auf einer Seite vorkommen müssen. (optional)
     * @param  string $stampsExclusive Liste mit Namen aller Stempel, von denen keiner auf einer Seite vorkommen darf. (optional)
     * @param  string $documentNameTerms Liste von Texten die alle im Dokumentennamen einer Seite vorkommen müssen. (optional)
     * @param  string $folderNameTerms Liste von Texten die alle im Ordner-Pfad einer Seite vorkommen müssen. (optional)
     * @param  string $location Pfad zu einem Ordner, auf den die Suche beschränkt werden soll (z. B. „/Muster GmbH/Rechnungen/“, „INBOX/Administrator“). Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  int $locationFolderId Ordner-Id, auf den die Suche beschränkt werden soll. Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  bool $recursive Bestimmt ob auch in Unterordner bei location gesucht wird. (optional, default to true)
     * @param  int $archiverId ID des Users der die zu suchenden Seiten archiviert haben muss. (optional)
     * @param  string $workflowName Name des Workflows in dem sich die zu suchenden Seiten aktuell befinden müssen. Durch Angabe von „*“ wird in allen Workflows gesucht. (optional)
     * @param  string $workflowState Name des Workflow-Knotens, in dem sich die zu suchenden Seiten aktuell befinden müssen. (optional)
     * @param  string $documentType Name oder Alias-Name eines Dokumenten-Typs, der allen zu suchenden Dokumenten zugewiesen sein muss. (optional)
     * @param  bool $includeTrash Gibt an, ob auch Dokumente im Papierkorb mit durchsucht werden sollen. (optional, default to false)
     * @param  string $externalId Text der in einer externen ID eines Dokuments vorkommen muss, damit es gefunden wird. (optional)
     * @param  string $externalMetadata Sucht Dokumente anhand ihrer externen Metadaten. Für jedes Metadatum in der Liste muss einem Dokument, damit es gefunden wird, ebenfalls ein Metadatum mit genau diesem Key zugeordnet sein und dessen Value den zu suchenden Value enthalten (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPOST'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Docbox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Docbox\Model\SearchPOST200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchPOSTWithHttpInfo($paginationSize = 10, $paginationPage = 0, $fulltextAll = null, $fulltextOne = null, $fulltextNone = null, $fromDate = null, $toDate = null, $followupTerms = null, $noteTerms = null, $keywordTerms = null, $stampsInclusive = null, $stampsExclusive = null, $documentNameTerms = null, $folderNameTerms = null, $location = null, $locationFolderId = null, $recursive = true, $archiverId = null, $workflowName = null, $workflowState = null, $documentType = null, $includeTrash = false, $externalId = null, $externalMetadata = null, string $contentType = self::contentTypes['searchPOST'][0])
    {
        $request = $this->searchPOSTRequest($paginationSize, $paginationPage, $fulltextAll, $fulltextOne, $fulltextNone, $fromDate, $toDate, $followupTerms, $noteTerms, $keywordTerms, $stampsInclusive, $stampsExclusive, $documentNameTerms, $folderNameTerms, $location, $locationFolderId, $recursive, $archiverId, $workflowName, $workflowState, $documentType, $includeTrash, $externalId, $externalMetadata, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Docbox\Model\SearchPOST200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Docbox\Model\SearchPOST200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Docbox\Model\SearchPOST200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Docbox\Model\SearchPOST200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Docbox\Model\SearchPOST200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchPOSTAsync
     *
     * @param  int $paginationSize Anzahl der Dokumente die im Ergebnis maximal zurückgegeben werden sollen, d.h. dieser Parameter gibt die Größe des Ergbnisfensters für das Paging des Suchergebnisses an. (optional, default to 10)
     * @param  int $paginationPage Gibt den Index des Ergebnisfensters an, welches angezeigt werden soll. Das erste Ergebnisfenster entspricht dabei dem Index 0. Durch Erhöhung des Index um 1 gelangt man zum nächsten Ergebnisfenster mit den nächsten Suchtreffern. Beispiel: Bei 27 gefundenen Dokumenten insgesamt und einer pagination-size von 10 liegt der Index des Ergebnisfensters zwischen 0 und 2 (optional, default to 0)
     * @param  string $fulltextAll Liste mit Texten, die alle gemeinsam auf jeder Trefferseite vorkommen müssen. (optional)
     * @param  string $fulltextOne Liste mit Texten, von denen mindestens einer auf jeder Trefferseite vorkommen muss. (optional)
     * @param  string $fulltextNone Liste mit Texten, von denen keiner auf den Trefferseiten vorkommen darf. (optional)
     * @param  string $fromDate Sucht nur nach Seiten deren Erstelldatum nach diesem Zeitpunkt liegt. (optional)
     * @param  string $toDate Sucht nur nach Seiten deren Erstelldatum vor diesem Zeitpunkt liegt. (optional)
     * @param  string $followupTerms Liste mit Texten die alle gemeinsam in den Wiedervorlage-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $noteTerms Liste mit Texten die alle gemeinsam in den Notiz-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $keywordTerms Liste von Texten die alle gemeinsam in den Schlagwörtern einer Seite vorkommen müssen. (optional)
     * @param  string $stampsInclusive Liste mit Namen aller Stempel, die gemeinsam auf einer Seite vorkommen müssen. (optional)
     * @param  string $stampsExclusive Liste mit Namen aller Stempel, von denen keiner auf einer Seite vorkommen darf. (optional)
     * @param  string $documentNameTerms Liste von Texten die alle im Dokumentennamen einer Seite vorkommen müssen. (optional)
     * @param  string $folderNameTerms Liste von Texten die alle im Ordner-Pfad einer Seite vorkommen müssen. (optional)
     * @param  string $location Pfad zu einem Ordner, auf den die Suche beschränkt werden soll (z. B. „/Muster GmbH/Rechnungen/“, „INBOX/Administrator“). Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  int $locationFolderId Ordner-Id, auf den die Suche beschränkt werden soll. Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  bool $recursive Bestimmt ob auch in Unterordner bei location gesucht wird. (optional, default to true)
     * @param  int $archiverId ID des Users der die zu suchenden Seiten archiviert haben muss. (optional)
     * @param  string $workflowName Name des Workflows in dem sich die zu suchenden Seiten aktuell befinden müssen. Durch Angabe von „*“ wird in allen Workflows gesucht. (optional)
     * @param  string $workflowState Name des Workflow-Knotens, in dem sich die zu suchenden Seiten aktuell befinden müssen. (optional)
     * @param  string $documentType Name oder Alias-Name eines Dokumenten-Typs, der allen zu suchenden Dokumenten zugewiesen sein muss. (optional)
     * @param  bool $includeTrash Gibt an, ob auch Dokumente im Papierkorb mit durchsucht werden sollen. (optional, default to false)
     * @param  string $externalId Text der in einer externen ID eines Dokuments vorkommen muss, damit es gefunden wird. (optional)
     * @param  string $externalMetadata Sucht Dokumente anhand ihrer externen Metadaten. Für jedes Metadatum in der Liste muss einem Dokument, damit es gefunden wird, ebenfalls ein Metadatum mit genau diesem Key zugeordnet sein und dessen Value den zu suchenden Value enthalten (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPOST'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchPOSTAsync($paginationSize = 10, $paginationPage = 0, $fulltextAll = null, $fulltextOne = null, $fulltextNone = null, $fromDate = null, $toDate = null, $followupTerms = null, $noteTerms = null, $keywordTerms = null, $stampsInclusive = null, $stampsExclusive = null, $documentNameTerms = null, $folderNameTerms = null, $location = null, $locationFolderId = null, $recursive = true, $archiverId = null, $workflowName = null, $workflowState = null, $documentType = null, $includeTrash = false, $externalId = null, $externalMetadata = null, string $contentType = self::contentTypes['searchPOST'][0])
    {
        return $this->searchPOSTAsyncWithHttpInfo($paginationSize, $paginationPage, $fulltextAll, $fulltextOne, $fulltextNone, $fromDate, $toDate, $followupTerms, $noteTerms, $keywordTerms, $stampsInclusive, $stampsExclusive, $documentNameTerms, $folderNameTerms, $location, $locationFolderId, $recursive, $archiverId, $workflowName, $workflowState, $documentType, $includeTrash, $externalId, $externalMetadata, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchPOSTAsyncWithHttpInfo
     *
     * @param  int $paginationSize Anzahl der Dokumente die im Ergebnis maximal zurückgegeben werden sollen, d.h. dieser Parameter gibt die Größe des Ergbnisfensters für das Paging des Suchergebnisses an. (optional, default to 10)
     * @param  int $paginationPage Gibt den Index des Ergebnisfensters an, welches angezeigt werden soll. Das erste Ergebnisfenster entspricht dabei dem Index 0. Durch Erhöhung des Index um 1 gelangt man zum nächsten Ergebnisfenster mit den nächsten Suchtreffern. Beispiel: Bei 27 gefundenen Dokumenten insgesamt und einer pagination-size von 10 liegt der Index des Ergebnisfensters zwischen 0 und 2 (optional, default to 0)
     * @param  string $fulltextAll Liste mit Texten, die alle gemeinsam auf jeder Trefferseite vorkommen müssen. (optional)
     * @param  string $fulltextOne Liste mit Texten, von denen mindestens einer auf jeder Trefferseite vorkommen muss. (optional)
     * @param  string $fulltextNone Liste mit Texten, von denen keiner auf den Trefferseiten vorkommen darf. (optional)
     * @param  string $fromDate Sucht nur nach Seiten deren Erstelldatum nach diesem Zeitpunkt liegt. (optional)
     * @param  string $toDate Sucht nur nach Seiten deren Erstelldatum vor diesem Zeitpunkt liegt. (optional)
     * @param  string $followupTerms Liste mit Texten die alle gemeinsam in den Wiedervorlage-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $noteTerms Liste mit Texten die alle gemeinsam in den Notiz-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $keywordTerms Liste von Texten die alle gemeinsam in den Schlagwörtern einer Seite vorkommen müssen. (optional)
     * @param  string $stampsInclusive Liste mit Namen aller Stempel, die gemeinsam auf einer Seite vorkommen müssen. (optional)
     * @param  string $stampsExclusive Liste mit Namen aller Stempel, von denen keiner auf einer Seite vorkommen darf. (optional)
     * @param  string $documentNameTerms Liste von Texten die alle im Dokumentennamen einer Seite vorkommen müssen. (optional)
     * @param  string $folderNameTerms Liste von Texten die alle im Ordner-Pfad einer Seite vorkommen müssen. (optional)
     * @param  string $location Pfad zu einem Ordner, auf den die Suche beschränkt werden soll (z. B. „/Muster GmbH/Rechnungen/“, „INBOX/Administrator“). Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  int $locationFolderId Ordner-Id, auf den die Suche beschränkt werden soll. Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  bool $recursive Bestimmt ob auch in Unterordner bei location gesucht wird. (optional, default to true)
     * @param  int $archiverId ID des Users der die zu suchenden Seiten archiviert haben muss. (optional)
     * @param  string $workflowName Name des Workflows in dem sich die zu suchenden Seiten aktuell befinden müssen. Durch Angabe von „*“ wird in allen Workflows gesucht. (optional)
     * @param  string $workflowState Name des Workflow-Knotens, in dem sich die zu suchenden Seiten aktuell befinden müssen. (optional)
     * @param  string $documentType Name oder Alias-Name eines Dokumenten-Typs, der allen zu suchenden Dokumenten zugewiesen sein muss. (optional)
     * @param  bool $includeTrash Gibt an, ob auch Dokumente im Papierkorb mit durchsucht werden sollen. (optional, default to false)
     * @param  string $externalId Text der in einer externen ID eines Dokuments vorkommen muss, damit es gefunden wird. (optional)
     * @param  string $externalMetadata Sucht Dokumente anhand ihrer externen Metadaten. Für jedes Metadatum in der Liste muss einem Dokument, damit es gefunden wird, ebenfalls ein Metadatum mit genau diesem Key zugeordnet sein und dessen Value den zu suchenden Value enthalten (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPOST'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchPOSTAsyncWithHttpInfo($paginationSize = 10, $paginationPage = 0, $fulltextAll = null, $fulltextOne = null, $fulltextNone = null, $fromDate = null, $toDate = null, $followupTerms = null, $noteTerms = null, $keywordTerms = null, $stampsInclusive = null, $stampsExclusive = null, $documentNameTerms = null, $folderNameTerms = null, $location = null, $locationFolderId = null, $recursive = true, $archiverId = null, $workflowName = null, $workflowState = null, $documentType = null, $includeTrash = false, $externalId = null, $externalMetadata = null, string $contentType = self::contentTypes['searchPOST'][0])
    {
        $returnType = '\OpenAPI\Client\Docbox\Model\SearchPOST200Response';
        $request = $this->searchPOSTRequest($paginationSize, $paginationPage, $fulltextAll, $fulltextOne, $fulltextNone, $fromDate, $toDate, $followupTerms, $noteTerms, $keywordTerms, $stampsInclusive, $stampsExclusive, $documentNameTerms, $folderNameTerms, $location, $locationFolderId, $recursive, $archiverId, $workflowName, $workflowState, $documentType, $includeTrash, $externalId, $externalMetadata, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchPOST'
     *
     * @param  int $paginationSize Anzahl der Dokumente die im Ergebnis maximal zurückgegeben werden sollen, d.h. dieser Parameter gibt die Größe des Ergbnisfensters für das Paging des Suchergebnisses an. (optional, default to 10)
     * @param  int $paginationPage Gibt den Index des Ergebnisfensters an, welches angezeigt werden soll. Das erste Ergebnisfenster entspricht dabei dem Index 0. Durch Erhöhung des Index um 1 gelangt man zum nächsten Ergebnisfenster mit den nächsten Suchtreffern. Beispiel: Bei 27 gefundenen Dokumenten insgesamt und einer pagination-size von 10 liegt der Index des Ergebnisfensters zwischen 0 und 2 (optional, default to 0)
     * @param  string $fulltextAll Liste mit Texten, die alle gemeinsam auf jeder Trefferseite vorkommen müssen. (optional)
     * @param  string $fulltextOne Liste mit Texten, von denen mindestens einer auf jeder Trefferseite vorkommen muss. (optional)
     * @param  string $fulltextNone Liste mit Texten, von denen keiner auf den Trefferseiten vorkommen darf. (optional)
     * @param  string $fromDate Sucht nur nach Seiten deren Erstelldatum nach diesem Zeitpunkt liegt. (optional)
     * @param  string $toDate Sucht nur nach Seiten deren Erstelldatum vor diesem Zeitpunkt liegt. (optional)
     * @param  string $followupTerms Liste mit Texten die alle gemeinsam in den Wiedervorlage-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $noteTerms Liste mit Texten die alle gemeinsam in den Notiz-Texten einer Seite vorkommen müssen. (optional)
     * @param  string $keywordTerms Liste von Texten die alle gemeinsam in den Schlagwörtern einer Seite vorkommen müssen. (optional)
     * @param  string $stampsInclusive Liste mit Namen aller Stempel, die gemeinsam auf einer Seite vorkommen müssen. (optional)
     * @param  string $stampsExclusive Liste mit Namen aller Stempel, von denen keiner auf einer Seite vorkommen darf. (optional)
     * @param  string $documentNameTerms Liste von Texten die alle im Dokumentennamen einer Seite vorkommen müssen. (optional)
     * @param  string $folderNameTerms Liste von Texten die alle im Ordner-Pfad einer Seite vorkommen müssen. (optional)
     * @param  string $location Pfad zu einem Ordner, auf den die Suche beschränkt werden soll (z. B. „/Muster GmbH/Rechnungen/“, „INBOX/Administrator“). Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  int $locationFolderId Ordner-Id, auf den die Suche beschränkt werden soll. Es wird auch in allen Unterordnern dieses Pfades gesucht (außer recursive ist auf false gesetzt). (optional)
     * @param  bool $recursive Bestimmt ob auch in Unterordner bei location gesucht wird. (optional, default to true)
     * @param  int $archiverId ID des Users der die zu suchenden Seiten archiviert haben muss. (optional)
     * @param  string $workflowName Name des Workflows in dem sich die zu suchenden Seiten aktuell befinden müssen. Durch Angabe von „*“ wird in allen Workflows gesucht. (optional)
     * @param  string $workflowState Name des Workflow-Knotens, in dem sich die zu suchenden Seiten aktuell befinden müssen. (optional)
     * @param  string $documentType Name oder Alias-Name eines Dokumenten-Typs, der allen zu suchenden Dokumenten zugewiesen sein muss. (optional)
     * @param  bool $includeTrash Gibt an, ob auch Dokumente im Papierkorb mit durchsucht werden sollen. (optional, default to false)
     * @param  string $externalId Text der in einer externen ID eines Dokuments vorkommen muss, damit es gefunden wird. (optional)
     * @param  string $externalMetadata Sucht Dokumente anhand ihrer externen Metadaten. Für jedes Metadatum in der Liste muss einem Dokument, damit es gefunden wird, ebenfalls ein Metadatum mit genau diesem Key zugeordnet sein und dessen Value den zu suchenden Value enthalten (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPOST'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchPOSTRequest($paginationSize = 10, $paginationPage = 0, $fulltextAll = null, $fulltextOne = null, $fulltextNone = null, $fromDate = null, $toDate = null, $followupTerms = null, $noteTerms = null, $keywordTerms = null, $stampsInclusive = null, $stampsExclusive = null, $documentNameTerms = null, $folderNameTerms = null, $location = null, $locationFolderId = null, $recursive = true, $archiverId = null, $workflowName = null, $workflowState = null, $documentType = null, $includeTrash = false, $externalId = null, $externalMetadata = null, string $contentType = self::contentTypes['searchPOST'][0])
    {

        if ($paginationSize !== null && $paginationSize > 100) {
            throw new \InvalidArgumentException('invalid value for "$paginationSize" when calling SearchApi.searchPOST, must be smaller than or equal to 100.');
        }
        if ($paginationSize !== null && $paginationSize < 1) {
            throw new \InvalidArgumentException('invalid value for "$paginationSize" when calling SearchApi.searchPOST, must be bigger than or equal to 1.');
        }
        
        if ($paginationPage !== null && $paginationPage < 0) {
            throw new \InvalidArgumentException('invalid value for "$paginationPage" when calling SearchApi.searchPOST, must be bigger than or equal to 0.');
        }
        























        $resourcePath = '/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $paginationSize,
            'pagination-size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $paginationPage,
            'pagination-page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fulltextAll,
            'fulltext-all', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fulltextOne,
            'fulltext-one', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fulltextNone,
            'fulltext-none', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fromDate,
            'from-date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toDate,
            'to-date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $followupTerms,
            'followup-terms', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $noteTerms,
            'note-terms', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $keywordTerms,
            'keyword-terms', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $stampsInclusive,
            'stamps-inclusive', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $stampsExclusive,
            'stamps-exclusive', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $documentNameTerms,
            'document-name-terms', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $folderNameTerms,
            'folder-name-terms', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $location,
            'location', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $locationFolderId,
            'location-folder-id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $recursive,
            'recursive', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $archiverId,
            'archiver-id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $workflowName,
            'workflow-name', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $workflowState,
            'workflow-state', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $documentType,
            'document-type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $includeTrash,
            'include-trash', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $externalId,
            'external-id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $externalMetadata,
            'external-metadata', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Cloud-ID');
        if ($apiKey !== null) {
            $headers['Cloud-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('API-Key');
        if ($apiKey !== null) {
            $headers['API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
